// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_mobx_shopping_list_app/test/data/datasources/home_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_mobx_shopping_list_app/core/api/rest_client.dart'
    as _i2;
import 'package:flutter_mobx_shopping_list_app/data/models/shopping_item_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestClient extends _i1.Mock implements _i2.RestClient {
  @override
  _i3.Future<List<_i4.ShoppingItemModel>> getShoppingItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getShoppingItems,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ShoppingItemModel>>.value(
            <_i4.ShoppingItemModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ShoppingItemModel>>.value(
                <_i4.ShoppingItemModel>[]),
      ) as _i3.Future<List<_i4.ShoppingItemModel>>);
  @override
  _i3.Future<void> createShoppingItem(_i4.ShoppingItemModel? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #createShoppingItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteShoppingItem(_i4.ShoppingItemModel? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteShoppingItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> updateShoppingItem(_i4.ShoppingItemModel? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShoppingItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
