name: flutter_mobx_shopping_list_app
description: Simple shopping list application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_route: ^7.8.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_mobx: ^2.0.6+5
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/icons/png/
    - assets/translations/
    - assets/.env
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
